name: alasfor
description: "AL_Asfor App"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  shared_preferences: ^2.2.2
  flutter_localization: ^0.3.3
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  flutter_staggered_grid_view: ^0.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  dio: ^5.9.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  build_runner: ^2.10.5

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajwal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajwal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajwal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajwal/Tajawal-Bold.ttf
          weight: 700

